name: flutter_clean_achitecture
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  camera: ^0.10.3+2
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  floor: ^1.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.1
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  logger: ^1.3.0
  retrofit: ^4.0.1
  safe_device: ^1.1.2
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/locales/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400
